name: road_wise
description: "A gamified road signs learning app with Duolingo-style experience"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.0
    # Database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.0

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  confetti: ^0.7.0

  # Navigation
  go_router: ^15.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0



  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true
